#!/usr/bin/env python3
"""
Simple test for the document service functionality.

This script tests the LaTeX-based document generation service directly.
"""

import sys
import os
import subprocess
from pathlib import Path

# Add the src directory to the Python path
sys.path.insert(0, str(Path(__file__).parent / "src"))

def test_latex_installation():
    """Check if LaTeX is installed and available."""
    print("Checking LaTeX installation...")
    
    try:
        result = subprocess.run(['pdflatex', '--version'], 
                              capture_output=True, text=True)
        if result.returncode == 0:
            print("✅ LaTeX (pdflatex) is installed and available")
            print(f"   Version info: {result.stdout.split('\n')[0]}")
            return True
        else:
            print("❌ LaTeX (pdflatex) is not available")
            return False
    except FileNotFoundError:
        print("❌ LaTeX (pdflatex) is not installed")
        print("   Please install LaTeX to use the document creator")
        print("   Run: ./install_latex.sh")
        return False

def test_template_creation():
    """Test LaTeX template creation."""
    print("\nTesting template creation...")
    
    try:
        # Check if templates directory exists
        templates_dir = Path("templates/latex")
        if templates_dir.exists():
            print("✅ Templates directory exists")
            
            # Check for template files
            template_files = list(templates_dir.glob("*.tex"))
            print(f"   Found {len(template_files)} template files:")
            for template in template_files:
                print(f"   - {template.name}")
            
            return True
        else:
            print("❌ Templates directory not found")
            return False
            
    except Exception as e:
        print(f"❌ Error testing template creation: {e}")
        return False

def test_simple_latex_compilation():
    """Test basic LaTeX compilation with a simple document."""
    print("\nTesting simple LaTeX compilation...")
    
    try:
        # Create a simple LaTeX document
        simple_tex = r"""\documentclass[11pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage{geometry}

\geometry{margin=1in}

\begin{document}

\title{Test Document}
\author{Generated by PocketFlow}
\date{\today}

\maketitle

\section{Introduction}
This is a test document to verify LaTeX compilation works correctly.

\section{Content}
The document creator is working properly if you can see this PDF.

\section{Conclusion}
LaTeX compilation test successful!

\end{document}"""
        
        # Write to temporary file
        test_file = "test_document.tex"
        with open(test_file, 'w') as f:
            f.write(simple_tex)
        
        # Compile to PDF
        result = subprocess.run(
            ['pdflatex', '-interaction=nonstopmode', test_file],
            capture_output=True,
            text=True
        )
        
        # Check if PDF was created
        pdf_file = "test_document.pdf"
        if os.path.exists(pdf_file):
            print("✅ LaTeX compilation successful")
            print(f"   PDF created: {pdf_file}")
            print(f"   File size: {os.path.getsize(pdf_file)} bytes")
            
            # Clean up
            for ext in ['.aux', '.log', '.out', '.tex']:
                cleanup_file = f"test_document{ext}"
                if os.path.exists(cleanup_file):
                    os.remove(cleanup_file)
            
            return True
        else:
            print("❌ LaTeX compilation failed")
            print(f"   Error: {result.stderr}")
            return False
            
    except Exception as e:
        print(f"❌ Error testing LaTeX compilation: {e}")
        return False

def test_document_service_import():
    """Test if we can import the document service."""
    print("\nTesting document service import...")
    
    try:
        from pocketflow.services.document_service import DocumentService
        print("✅ DocumentService import successful")
        
        # Try to create an instance
        doc_service = DocumentService()
        print("✅ DocumentService instantiation successful")
        
        return True
        
    except Exception as e:
        print(f"❌ Error importing DocumentService: {e}")
        return False

def test_document_type_detection():
    """Test document type detection logic."""
    print("\nTesting document type detection...")
    
    try:
        from pocketflow.services.document_service import DocumentService
        
        doc_service = DocumentService()
        
        test_cases = [
            ("Create a business report about AI", "business_report"),
            ("Generate a technical report on ML", "technical_report"),
            ("Write a report about climate", "report"),
            ("Financial analysis of markets", "business_report"),
            ("Research methodology for data science", "technical_report")
        ]
        
        all_passed = True
        for prompt, expected_type in test_cases:
            detected_type = doc_service._determine_document_type(prompt)
            status = "✅" if detected_type == expected_type else "❌"
            print(f"{status} '{prompt}' -> {detected_type} (expected: {expected_type})")
            if detected_type != expected_type:
                all_passed = False
        
        return all_passed
        
    except Exception as e:
        print(f"❌ Error testing document type detection: {e}")
        return False

def test_fallback_content():
    """Test fallback content generation."""
    print("\nTesting fallback content generation...")
    
    try:
        from pocketflow.services.document_service import DocumentService
        
        doc_service = DocumentService()
        
        # Test fallback content for different document types
        test_cases = [
            ("business_report", "Business analysis"),
            ("technical_report", "Technical analysis"),
            ("report", "General report")
        ]
        
        for doc_type, prompt in test_cases:
            content = doc_service._create_fallback_content(prompt, doc_type)
            print(f"✅ Fallback content for {doc_type}:")
            print(f"   Title: {content.get('title', 'N/A')}")
            print(f"   Abstract: {content.get('abstract', 'N/A')[:50]}...")
        
        return True
        
    except Exception as e:
        print(f"❌ Error in fallback content generation: {e}")
        return False

if __name__ == "__main__":
    print("Document Creator Simple Test Suite")
    print("=" * 50)
    
    # Test LaTeX installation
    latex_ok = test_latex_installation()
    
    # Test template creation
    template_ok = test_template_creation()
    
    # Test simple LaTeX compilation
    compilation_ok = test_simple_latex_compilation()
    
    # Test document service import
    import_ok = test_document_service_import()
    
    # Test document type detection
    detection_ok = test_document_type_detection()
    
    # Test fallback content
    fallback_ok = test_fallback_content()
    
    print("\n" + "=" * 50)
    print("Test Results:")
    print(f"LaTeX Installation: {'✅ PASS' if latex_ok else '❌ FAIL'}")
    print(f"Template Creation: {'✅ PASS' if template_ok else '❌ FAIL'}")
    print(f"LaTeX Compilation: {'✅ PASS' if compilation_ok else '❌ FAIL'}")
    print(f"Service Import: {'✅ PASS' if import_ok else '❌ FAIL'}")
    print(f"Type Detection: {'✅ PASS' if detection_ok else '❌ FAIL'}")
    print(f"Fallback Content: {'✅ PASS' if fallback_ok else '❌ FAIL'}")
    
    if all([latex_ok, template_ok, compilation_ok, import_ok, detection_ok, fallback_ok]):
        print("\n🎉 All tests passed! Document creator is ready to use.")
    else:
        print("\n⚠️  Some tests failed. Please check the issues above.")
    
    print("\nTest suite completed!") 