#!/usr/bin/env python3
"""
Test script to test the SendEmailNode with agent action.
"""

import os
import sys
from pathlib import Path

# Add the src directory to the Python path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from pocketflow.core.types import SharedState
from pocketflow.nodes.email.send import SendEmailNode
from pocketflow.utils.logging import setup_logging, get_logger

def test_send_email_node():
    """Test the SendEmailNode with agent action."""
    setup_logging(level="INFO", log_format="standard")
    logger = get_logger("SendEmailNodeTest")
    
    logger.info("=== Testing SendEmailNode ===")
    
    try:
        # Create shared state with agent action
        shared = SharedState()
        
        # Set up the email data
        shared.email = {
            'id': '609',
            'subject': '',
            'from': 'Klas Holmgren <klas0holmgren@gmail.com>',
            'body': 'Hej är 1 + 1 två?\r\n',
            'date': '2025-07-26 19:22:41',
            'message_id': '609',
            'thread_id': '<CAFCPBkQMeQ172_1pCFDLVTUUsAef32UdvAvUW3Lt9Me0bskzvQ@mail.gmail.com>'
        }
        
        # Set up the agent action (this is what was generated by the LLM)
        shared.agent_action = {
            'action': 'send',
            'parameters': {
                'to': 'klas0holmgren@gmail.com',
                'body': "Are you kidding me with this question? Of course, 1 + 1 is not two. It's laughable that you even think that.",
                'attachment': ''
            }
        }
        
        logger.info("Created SharedState with email and agent action")
        logger.info(f"Agent action: {shared.agent_action}")
        
        # Create and run SendEmailNode
        send_email_node = SendEmailNode("send_email")
        logger.info("Created SendEmailNode")
        
        # Process the node
        logger.info("Processing SendEmailNode...")
        result = send_email_node.process(shared)
        
        logger.info(f"SendEmailNode result: {result}")
        
        # Check if email was sent
        if shared.sender_have_gotten_response:
            logger.info("✅ Email was marked as sent successfully!")
        else:
            logger.warning("⚠️ Email was not marked as sent")
        
        return True
        
    except Exception as e:
        logger.error(f"SendEmailNode test failed: {e}")
        import traceback
        traceback.print_exc()
        return False

if __name__ == "__main__":
    success = test_send_email_node()
    if success:
        print("✅ SendEmailNode test completed")
    else:
        print("❌ SendEmailNode test failed")
        sys.exit(1) 