"""
Document generation service using LaTeX templates.

This service generates professional PDF documents using LaTeX templates.
"""

import os
import subprocess
import tempfile
from typing import Optional, Dict, Any, List
from pathlib import Path
import json
import shutil

from ..core.types import ContentGenerationRequest
from ..config.settings import get_settings
from ..utils.errors import ContentGenerationError
from ..utils.logging import get_logger


class DocumentService:
    """Service for generating PDF documents using LaTeX templates."""
    
    def __init__(self):
        self.settings = get_settings()
        self.logger = get_logger("DocumentService")
        self._ensure_output_directory()
        self._ensure_templates_directory()
    
    def _ensure_output_directory(self):
        """Ensure the output directory exists."""
        output_dir = Path(self.settings.CONTENT_OUTPUT_DIR)
        output_dir.mkdir(parents=True, exist_ok=True)
        self.logger.info(f"Document output directory: {output_dir}")
    
    def _ensure_templates_directory(self):
        """Ensure the templates directory exists."""
        templates_dir = Path("templates/latex")
        templates_dir.mkdir(parents=True, exist_ok=True)
        self.logger.info(f"LaTeX templates directory: {templates_dir}")
        
        # Create default templates if they don't exist
        self._create_default_templates()
    
    def _create_default_templates(self):
        """Create default LaTeX templates."""
        templates_dir = Path("templates/latex")
        
        # Report template
        report_template = templates_dir / "report.tex"
        if not report_template.exists():
            self._create_report_template(report_template)
        
        # Business report template
        business_template = templates_dir / "business_report.tex"
        if not business_template.exists():
            self._create_business_report_template(business_template)
        
        # Technical report template
        technical_template = templates_dir / "technical_report.tex"
        if not technical_template.exists():
            self._create_technical_report_template(technical_template)
    
    def _create_report_template(self, template_path: Path):
        """Create a basic report template."""
        template_content = r"""\documentclass[11pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{geometry}
\usepackage{graphicx}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{booktabs}
\usepackage{hyperref}
\usepackage{fancyhdr}
\usepackage{titlesec}
\usepackage{enumitem}
\usepackage{listings}
\usepackage{xcolor}

\geometry{margin=1in}

% Header and footer
\pagestyle{fancy}
\fancyhf{}
\rhead{\thepage}
\lhead{Generated Report}
\renewcommand{\headrulewidth}{0.4pt}

% Title formatting
\titleformat{\section}{\Large\bfseries}{\thesection}{1em}{}
\titleformat{\subsection}{\large\bfseries}{\thesubsection}{1em}{}

% Code listing style
\lstset{
    basicstyle=\ttfamily\small,
    breaklines=true,
    frame=single,
    numbers=left,
    numberstyle=\tiny,
    keywordstyle=\color{blue},
    commentstyle=\color{green!60!black},
    stringstyle=\color{red}
}

\begin{document}

\title{REPORT_TITLE}
\author{Generated by PocketFlow}
\date{\today}

\maketitle

\begin{abstract}
REPORT_ABSTRACT
\end{abstract}

\tableofcontents
\newpage

REPORT_CONTENT

\end{document}"""
        
        with open(template_path, 'w') as f:
            f.write(template_content)
    
    def _create_business_report_template(self, template_path: Path):
        """Create a business report template."""
        template_content = r"""\documentclass[11pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{geometry}
\usepackage{graphicx}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{booktabs}
\usepackage{hyperref}
\usepackage{fancyhdr}
\usepackage{titlesec}
\usepackage{enumitem}
\usepackage{longtable}
\usepackage{array}

\geometry{margin=1in}

% Header and footer
\pagestyle{fancy}
\fancyhf{}
\rhead{\thepage}
\lhead{Business Report}
\renewcommand{\headrulewidth}{0.4pt}

% Title formatting
\titleformat{\section}{\Large\bfseries}{\thesection}{1em}{}
\titleformat{\subsection}{\large\bfseries}{\thesubsection}{1em}{}

\begin{document}

\title{BUSINESS_REPORT_TITLE}
\author{Generated by PocketFlow}
\date{\today}

\maketitle

\begin{abstract}
BUSINESS_REPORT_ABSTRACT
\end{abstract}

\tableofcontents
\newpage

\section{Executive Summary}
EXECUTIVE_SUMMARY

\section{Introduction}
INTRODUCTION

\section{Analysis}
ANALYSIS

\section{Recommendations}
RECOMMENDATIONS

\section{Conclusion}
CONCLUSION

\end{document}"""
        
        with open(template_path, 'w') as f:
            f.write(template_content)
    
    def _create_technical_report_template(self, template_path: Path):
        """Create a technical report template."""
        template_content = r"""\documentclass[11pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{geometry}
\usepackage{graphicx}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{booktabs}
\usepackage{hyperref}
\usepackage{fancyhdr}
\usepackage{titlesec}
\usepackage{enumitem}
\usepackage{listings}
\usepackage{xcolor}
\usepackage{algorithm}
\usepackage{algorithmic}

\geometry{margin=1in}

% Header and footer
\pagestyle{fancy}
\fancyhf{}
\rhead{\thepage}
\lhead{Technical Report}
\renewcommand{\headrulewidth}{0.4pt}

% Title formatting
\titleformat{\section}{\Large\bfseries}{\thesection}{1em}{}
\titleformat{\subsection}{\large\bfseries}{\thesubsection}{1em}{}

% Code listing style
\lstset{
    basicstyle=\ttfamily\small,
    breaklines=true,
    frame=single,
    numbers=left,
    numberstyle=\tiny,
    keywordstyle=\color{blue},
    commentstyle=\color{green!60!black},
    stringstyle=\color{red}
}

\begin{document}

\title{TECHNICAL_REPORT_TITLE}
\author{Generated by PocketFlow}
\date{\today}

\maketitle

\begin{abstract}
TECHNICAL_REPORT_ABSTRACT
\end{abstract}

\tableofcontents
\newpage

\section{Introduction}
INTRODUCTION

\section{Methodology}
METHODOLOGY

\section{Results}
RESULTS

\section{Discussion}
DISCUSSION

\section{Conclusion}
CONCLUSION

\end{document}"""
        
        with open(template_path, 'w') as f:
            f.write(template_content)
    
    def generate_document(self, request: ContentGenerationRequest) -> Optional[str]:
        """
        Generate a PDF document using LaTeX templates.
        
        Args:
            request: ContentGenerationRequest with document parameters
            
        Returns:
            Path to the generated PDF file, or None if generation failed
        """
        try:
            self.logger.info(f"Generating document: {request.prompt}")
            
            # Determine document type and template
            doc_type = self._determine_document_type(request.prompt)
            template_path = self._get_template_path(doc_type)
            
            # Generate content using LLM
            document_content = self._generate_document_content(request.prompt, doc_type)
            
            # Create LaTeX file
            latex_file = self._create_latex_file(template_path, document_content, request.prompt)
            
            # Compile to PDF
            pdf_path = self._compile_latex_to_pdf(latex_file)
            
            if pdf_path and os.path.exists(pdf_path):
                self.logger.info(f"Document generated successfully: {pdf_path}")
                return pdf_path
            else:
                self.logger.error("PDF compilation failed")
                return None
                
        except Exception as e:
            self.logger.error(f"Document generation error: {e}")
            return None
    
    def _determine_document_type(self, prompt: str) -> str:
        """Determine the type of document to generate based on the prompt."""
        prompt_lower = prompt.lower()
        
        if any(word in prompt_lower for word in ["business", "financial", "market", "company"]):
            return "business_report"
        elif any(word in prompt_lower for word in ["technical", "research", "analysis", "data"]):
            return "technical_report"
        else:
            return "report"
    
    def _get_template_path(self, doc_type: str) -> Path:
        """Get the path to the appropriate LaTeX template."""
        templates_dir = Path("templates/latex")
        
        if doc_type == "business_report":
            return templates_dir / "business_report.tex"
        elif doc_type == "technical_report":
            return templates_dir / "technical_report.tex"
        else:
            return templates_dir / "report.tex"
    
    def _generate_document_content(self, prompt: str, doc_type: str) -> Dict[str, str]:
        """Generate document content using LLM."""
        from ..services import llm_service
        
        # Check if this is a research-based document
        is_research_based = "research findings" in prompt.lower() or "research topic" in prompt.lower() or "investigation findings" in prompt.lower()
        
        # Create a structured prompt for document generation
        if doc_type == "business_report":
            if is_research_based:
                system_prompt = """You are a professional business analyst. Generate a comprehensive business report based on research findings provided by the user. 
                
                The user has conducted research and wants you to create a business report incorporating those findings. Structure the content with the following sections:
                - Executive Summary (2-3 paragraphs incorporating key research insights)
                - Introduction (1-2 paragraphs with research context)
                - Analysis (3-4 paragraphs using research data to support key points)
                - Recommendations (2-3 actionable recommendations based on research)
                - Conclusion (1-2 paragraphs summarizing research-based insights)
                
                Make sure to:
                1. Incorporate the research findings throughout the document
                2. Use research data to support your analysis and conclusions
                3. Create a professional, well-structured business report
                4. Ensure all claims are supported by the research data
                
                Format the response as JSON with keys: title, abstract, executive_summary, introduction, analysis, recommendations, conclusion"""
            else:
                system_prompt = """You are a professional business analyst. Generate a comprehensive business report based on the user's request. 
                Structure the content with the following sections:
                - Executive Summary (2-3 paragraphs)
                - Introduction (1-2 paragraphs)
                - Analysis (3-4 paragraphs with key points)
                - Recommendations (2-3 actionable recommendations)
                - Conclusion (1-2 paragraphs)
                
                Format the response as JSON with keys: title, abstract, executive_summary, introduction, analysis, recommendations, conclusion"""
            
        elif doc_type == "technical_report":
            if is_research_based:
                system_prompt = """You are a technical writer. Generate a comprehensive technical report based on research findings provided by the user.
                
                The user has conducted research and wants you to create a technical report incorporating those findings. Structure the content with the following sections:
                - Introduction (1-2 paragraphs with research context)
                - Methodology (1-2 paragraphs describing research approach)
                - Results (2-3 paragraphs presenting research findings with technical details)
                - Discussion (2-3 paragraphs analyzing the research results)
                - Conclusion (1-2 paragraphs summarizing technical insights from research)
                
                Make sure to:
                1. Incorporate the research findings throughout the document
                2. Use research data to support your technical analysis
                3. Create a professional, well-structured technical report
                4. Ensure all technical claims are supported by the research data
                
                Format the response as JSON with keys: title, abstract, introduction, methodology, results, discussion, conclusion"""
            else:
                system_prompt = """You are a technical writer. Generate a comprehensive technical report based on the user's request.
                Structure the content with the following sections:
                - Introduction (1-2 paragraphs)
                - Methodology (1-2 paragraphs)
                - Results (2-3 paragraphs with technical details)
                - Discussion (2-3 paragraphs analyzing the results)
                - Conclusion (1-2 paragraphs)
                
                Format the response as JSON with keys: title, abstract, introduction, methodology, results, discussion, conclusion"""
            
        else:
            if is_research_based:
                system_prompt = """You are a professional report writer. Generate a comprehensive report based on research findings provided by the user.
                
                The user has conducted research and wants you to create a report incorporating those findings. Structure the content with the following sections:
                - Abstract (1 paragraph summarizing research-based insights)
                - Main content (3-4 paragraphs using research data to support key points)
                - Summary (1-2 paragraphs summarizing research-based conclusions)
                
                Make sure to:
                1. Incorporate the research findings throughout the document
                2. Use research data to support your analysis
                3. Create a professional, well-structured report
                4. Ensure all claims are supported by the research data
                
                Format the response as JSON with keys: title, abstract, content"""
            else:
                system_prompt = """You are a professional report writer. Generate a comprehensive report based on the user's request.
                Structure the content with the following sections:
                - Abstract (1 paragraph)
                - Main content (3-4 paragraphs with key points)
                - Summary (1-2 paragraphs)
                
                Format the response as JSON with keys: title, abstract, content"""
        
        user_prompt = f"Generate a {doc_type.replace('_', ' ')} about: {prompt}"
        
        try:
            # Create a combined prompt
            combined_prompt = f"{system_prompt}\n\n{user_prompt}"
            response = llm_service.call_llm(combined_prompt)
            
            # Try to parse JSON response
            try:
                import json
                content = json.loads(response)
                return content
            except json.JSONDecodeError:
                # Fallback: create simple content structure
                return self._create_fallback_content(prompt, doc_type)
                
        except Exception as e:
            self.logger.warning(f"LLM call failed: {e}")
            return self._create_fallback_content(prompt, doc_type)
    
    def _create_fallback_content(self, prompt: str, doc_type: str) -> Dict[str, str]:
        """Create fallback content when LLM fails."""
        if doc_type == "business_report":
            return {
                "title": f"Business Report: {prompt}",
                "abstract": f"This report analyzes {prompt} from a business perspective.",
                "executive_summary": f"This executive summary provides an overview of {prompt}.",
                "introduction": f"This report examines {prompt} in detail.",
                "analysis": f"Analysis of {prompt} reveals important insights.",
                "recommendations": "Based on the analysis, we recommend further investigation.",
                "conclusion": f"In conclusion, {prompt} presents significant opportunities."
            }
        elif doc_type == "technical_report":
            return {
                "title": f"Technical Report: {prompt}",
                "abstract": f"This technical report examines {prompt}.",
                "introduction": f"This report provides a technical analysis of {prompt}.",
                "methodology": "The analysis was conducted using standard technical methods.",
                "results": f"Results show that {prompt} has technical implications.",
                "discussion": "The findings suggest important technical considerations.",
                "conclusion": f"Technical analysis of {prompt} reveals key insights."
            }
        else:
            return {
                "title": f"Report: {prompt}",
                "abstract": f"This report provides information about {prompt}.",
                "content": f"This report examines {prompt} in detail. The analysis reveals important insights and considerations."
            }
    
    def _create_latex_file(self, template_path: Path, content: Dict[str, str], original_prompt: str) -> str:
        """Create a LaTeX file from template and content."""
        # Read template
        with open(template_path, 'r') as f:
            template_content = f.read()
        
        # Replace placeholders with content
        if "business_report" in template_path.name:
            latex_content = template_content.replace("BUSINESS_REPORT_TITLE", content.get("title", "Business Report"))
            latex_content = latex_content.replace("BUSINESS_REPORT_ABSTRACT", content.get("abstract", ""))
            latex_content = latex_content.replace("EXECUTIVE_SUMMARY", content.get("executive_summary", ""))
            latex_content = latex_content.replace("INTRODUCTION", content.get("introduction", ""))
            latex_content = latex_content.replace("ANALYSIS", content.get("analysis", ""))
            latex_content = latex_content.replace("RECOMMENDATIONS", content.get("recommendations", ""))
            latex_content = latex_content.replace("CONCLUSION", content.get("conclusion", ""))
            
        elif "technical_report" in template_path.name:
            latex_content = template_content.replace("TECHNICAL_REPORT_TITLE", content.get("title", "Technical Report"))
            latex_content = latex_content.replace("TECHNICAL_REPORT_ABSTRACT", content.get("abstract", ""))
            latex_content = latex_content.replace("INTRODUCTION", content.get("introduction", ""))
            latex_content = latex_content.replace("METHODOLOGY", content.get("methodology", ""))
            latex_content = latex_content.replace("RESULTS", content.get("results", ""))
            latex_content = latex_content.replace("DISCUSSION", content.get("discussion", ""))
            latex_content = latex_content.replace("CONCLUSION", content.get("conclusion", ""))
            
        else:
            latex_content = template_content.replace("REPORT_TITLE", content.get("title", "Report"))
            latex_content = latex_content.replace("REPORT_ABSTRACT", content.get("abstract", ""))
            latex_content = latex_content.replace("REPORT_CONTENT", content.get("content", ""))
        
        # Create temporary LaTeX file
        import uuid
        latex_filename = f"document_{uuid.uuid4().hex[:8]}.tex"
        latex_path = os.path.join(self.settings.CONTENT_OUTPUT_DIR, latex_filename)
        
        with open(latex_path, 'w') as f:
            f.write(latex_content)
        
        return latex_path
    
    def _compile_latex_to_pdf(self, latex_file: str) -> Optional[str]:
        """Compile LaTeX file to PDF."""
        try:
            # Get the directory and filename
            latex_dir = os.path.dirname(latex_file)
            latex_filename = os.path.basename(latex_file)
            pdf_filename = latex_filename.replace('.tex', '.pdf')
            pdf_path = os.path.join(latex_dir, pdf_filename)
            
            # Run pdflatex
            result = subprocess.run(
                ['pdflatex', '-interaction=nonstopmode', '-output-directory', latex_dir, latex_file],
                capture_output=True,
                text=True,
                cwd=latex_dir
            )
            
            if result.returncode == 0 and os.path.exists(pdf_path):
                # Clean up auxiliary files
                self._cleanup_latex_files(latex_dir, latex_filename)
                return pdf_path
            else:
                self.logger.error(f"LaTeX compilation failed: {result.stderr}")
                return None
                
        except Exception as e:
            self.logger.error(f"LaTeX compilation error: {e}")
            return None
    
    def _cleanup_latex_files(self, directory: str, base_filename: str):
        """Clean up auxiliary LaTeX files."""
        base_name = base_filename.replace('.tex', '')
        extensions = ['.aux', '.log', '.out', '.toc', '.lof', '.lot']
        
        for ext in extensions:
            file_path = os.path.join(directory, base_name + ext)
            if os.path.exists(file_path):
                try:
                    os.remove(file_path)
                except Exception as e:
                    self.logger.warning(f"Failed to remove {file_path}: {e}")
    
    def get_supported_document_types(self) -> List[str]:
        """Get list of supported document types."""
        return ["report", "business_report", "technical_report"]
    
    def validate_document_type(self, doc_type: str) -> bool:
        """Validate if the document type is supported."""
        return doc_type in self.get_supported_document_types() 